services:
  back:
    container_name: rsxback
    build:
      context: .
    network_mode: host
    environment:
      - DATABASE_URL=mongodb://graveddiger:2947DarthRevan@localhost:27017/rsx?replicaSet=rs1&authSource=admin&directConnection=true
    volumes:
      - ./temp:/home/app/temp
      - ./logs:/home/app/logs
